Update kubectl pre-command hook to only run if not existed

diff --git a/.buildkite/hooks/pre-command b/.buildkite/hooks/pre-command
--- a/.buildkite/hooks/pre-command
+++ b/.buildkite/hooks/pre-command
@@ -13,9 +13,17 @@ ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose -f
 # Install kubectl
 # https://kubernetes.io/docs/tasks/tools/install-kubectl/
 # Removed `sudo` because running as root.
-echo "Installing kubectl"
-apt-get update && apt-get install -y apt-transport-https gnupg2
-curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
-echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list
-apt-get update
-apt-get install -y kubectl
+function install-kubectl {
+  echo "Installing kubectl"
+  apt-get update && apt-get install -y apt-transport-https gnupg2
+  curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
+  echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list
+  apt-get update
+  apt-get install -y kubectl
+}
+
+if ! command -v kubectl &> /dev/null
+then
+  echo "`kubectl` could not be found, installing."
+  install-kubectl
+fi
